# Blog settings
permalink: /blog/:title

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
highlighter: rouge

# My variables
name: Danny Vilela

# Site settings
title: dataframe | danny's blog
description: "Hey! Here's Danny Vilela's blog on data science, machine learning, and exploratory data analysis. Check it out!"
email: danny.vilela@nyu.edu
baseurl: ""
url: "https://dataframing.github.io"

# Gems
gems:
  - jekyll-seo-tag
  
collections:
  books:
    output: false
